In [75]:
import numpy as np
from collections import Counter

vocab = Counter()

text = "Hi from Brazil from"
text = text.lower()

#Get all words
for word in text.split(' '):
    vocab[word]+=1
    
print 'vocab ->', vocab

vocab -> Counter({'from': 2, 'brazil': 1, 'hi': 1})


In [76]:
#Convert words to indexes
def get_word_2_index(vocab):
    word2index = {}
    for i,word in enumerate(vocab):
        word2index[word] = i
    return word2index

#Now we have an index
word2index = get_word_2_index(vocab)

print 'word2index ->', word2index

word2index -> {'brazil': 0, 'hi': 1, 'from': 2}


In [78]:
total_words = len(vocab)

print "Total distinct words:", total_words

Total distinct words: 3


In [79]:
#This is how we create a numpy array (our matrix)
matrix = np.zeros((total_words),dtype=float)

print matrix

[ 0.  0.  0.]


In [80]:
#Now we fill the values
for word in text.split():
    matrix[word2index[word]] += 1
    
print matrix

[ 1.  1.  2.]


In [81]:
matrix = np.zeros((total_words),dtype=float)

text = "Hi"
text = text.lower()

for word in text.split():
    matrix[word2index[word]] += 1
    
matrix

array([ 0.,  1.,  0.])